---
title: Set up respirometry schedule apps.
#author: Matías I. Muñoz
output: github_document
#date: "`r Sys.Date()`"
editor_options:
  chunk_output_type: console
---

<!-- Short Description  -->
Shiny apps for creating the .txt files that control the respirometry schedule.

<!-- *Updated on `r Sys.time()`* -->

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}

library(rmarkdown)

knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%"
)
```


<!-- ## Table of contents -->
<!-- * [General info](#general-info) -->
<!--   * [Analyses](#Analyses) -->
<!--     * [To do list](#to-do-list) -->
<!--       * [Contact](#contact) -->

<!-- ## General info -->

<!-- General information about the project (study system, goals, etc) -->

<!-- ## Scripts -->

<!-- * Analysis 1 -->

<!-- ## In progress -->

<!-- *  Something not finished yet -->

<!-- ## To-do list -->

<!-- * Do the next analysis -->

## Status
Project is: _in progress_


## How to create a desktop icon

To run the Shiny app more easily, you can create a desktop shortcut that launches it directly from R.

#### _Step 1: Download the scripts_

Download all required `.R` files and store them in a stable folder on your computer (e.g., Documents or Projects).

#### _Step 2: Locate Rscript on your computer_

Find the path to `Rscript.exe`. It is usually located in a folder like:

```
C:\Program Files\R\R-4.5.3\bin\Rscript.exe
```

(Your version number may differ.)

#### _Step 3: Create a shortcut_

1. Right-click on your Desktop  
2. Select **New → Shortcut**  
3. In the location field, paste:

```
"C:\Program Files\R\R-4.5.3\bin\Rscript.exe" "C:\path\to\the\app\run_app.R"
```

Replace `"C:\path\to\the\app\run_app.R"` with the actual path to your script.

#### _Step 4: Name your shortcut_

Give it a meaningful name (e.g., *Respirometry App*) and assign an icon (some images (.ico) are available in the 'App_icons' folder in this repository).

#### _Step 5: Done_

Double-click the shortcut to launch the Shiny app. 

One reason launching may fail is if the required libraries are not installed, so if that happens make sure to check the code and install the required libraries.


## Contact
Created by [Matías I. Muñoz](https://sites.google.com/view/matiasmunozsandoval/home)